# Generated by Django 2.2.6 on 2022-02-03 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created"],
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
        migrations.RenameField(
            model_name="post", old_name="pub_date", new_name="created"
        ),
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Выберите дату",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Выберите дату",
                verbose_name="Дата создания",
            ),
        ),
    ]
